### PR TITLE
[KK] Adding nypl log formatter

### PR DESCRIPTION
**Pull request by emu47**
One note: Changing .error logs to .fatal due to rails throwing fatal errors. This should make it easier to set up the metrics.

### CODE REVIEW

**Comment by ktp242** [comment]
Looks good. Should we review and see if there's any other `.error` needs to be updated to `.fatal`? Or they are all in this PR?

**Comment by emu47** [comment]
They should all be in this PR. I think I changed them all.

**Review by ktp242 — APPROVED** [review]

**Comment by nodanaonlyzuul** [comment]
Are either of you seeing this in your logs?:

```
ebapp_1  | App 415 output: [ 2018-09-19 14:50:08.3929 415/0x0000000001d9dfb8(Worker 1) utils.rb ]: *** Exception NoMethodError in Rack application object (undefined method `silence' for #<NyplLogFormatter:0x0000000003c7a058>) (process 415, thread 0x0000000001d9dfb8(Worker 1)):
webapp_1  | App 415 output: 	from /usr/local/rvm/gems/ruby-2.5.1/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:11:in `call'
webapp_1  | App 415 output: 	from /usr/local/rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
webapp_1  | App 415 output: 	from /usr/local/rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
webapp_1  | App 415 output: 	from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
webapp_1  | App 415 output: 	from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
webapp_1  | App 415 output: 	from /usr/local/rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
webapp_1  | App 415 output: 	from /usr/local/rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
webapp_1  | App 415 output: 	from /usr/local/rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/static.rb:127:in `call'
webapp_1  | App 415 output: 	from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
webapp_1  | App 415 output: 	from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/engine.rb:524:in `call'
webapp_1  | App 415 output: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
webapp_1  | App 415 output: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
webapp_1  | App 415 output: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
webapp_1  | App 415 output: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
webapp_1  | App 415 output: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by nodanaonlyzuul** [comment]
Can you add `RAILS_LOG_TO_STDOUT=true` to your .env file and see if that's what causes it?

**Pull request merged**
